server:
    port: 8888
spring:
    #数据库配置
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/crady?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #最大活跃连接数
            max-active: 100
            #初始连接数
            initial-size: 1
            #最大连接等待超时时间
            max-wait: 60000
            #打开PSCache，并且指定每个连接PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            #最小空闲连接
            min-idle: 1
    redis:
        host: 192.168.221.188
        port: 6379
        password: foobared
        #redis超时时间,单位毫秒
        timeout: 1000
        jedis:
            #连接池配置
            pool:
                min-idle: 1
                max-idle: 8
                max-active: 8
                max-wait: 2000
    #缓存管理器配置，缓存注解使用
    cache:
        type: redis
        cache-names: redisCache
        redis:
            #是否允许redis缓存空值
            cache-null-values: true
            #是否启用键值前缀
            use-key-prefix: true
            #键值前缀
            key-prefix:
            #缓存超时时间戳，配置0为不设置超时时间
            time-to-live: 0
#mybatis配置
mybatis:
    mapper-locations: classpath:sqlmapper/*.xml
    configuration:
        #懒加载
        aggressive-lazy-loading: true
        #执行器类型
        default-executor-type: simple

#分页插件
pagehelper:
    #数据库类型
    helper-dialect: mysql
    #合理化参数设置reasonable，如果pageNum<0时查询第一页，大于最大一页时查询最后一页
    reasonable: true

#监控端点,默认情况下只会启用 health和info两个端点
management:
    endpoints:
        web:
            exposure:
                #设置需要暴漏的端点，"*"代表所有端口，也可以以列表形式表示如："beans","evn"
                include: "*"
                #设置不需要暴漏的端点，可以使列表
                exclude: "env"
            base-path: /actuator
    #设置是否可以通过URL优雅关闭，只能使用Post方式关闭
    endpoint:
        shutdown:
            enabled: true

logging:
    level:
        com.crady: debug
