package com.crady.mapper;

import com.crady.entity.UserEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMapper {

    //simple query
    List<UserEntity> selectAll();
    List<UserEntity> selectByIdList(List<Integer> list);
    List<UserEntity> selectByIdArray(Integer[] ids);
    List<UserEntity> selectChooseDemo(@Param("name")String name,@Param("age")Integer age);

    //conplex query 1:1
    UserEntity selectUserAccount1(@Param("id")Integer id,@Param("name")String name);
    List<UserEntity> selectUserAccount2(Integer[] ids);
    List<UserEntity> selectUserHealth(Integer[] ids);

    //conplex query 1:N
    UserEntity selectUserJob1(@Param("id")Integer id);
    List<UserEntity> selectUserJob2(Integer[] ids);

    int insertSelectiveGetId(UserEntity record);

    int insertBatchGetId(List<UserEntity> users);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserEntity record);
}