package com.crady.mapper;

import com.crady.entity.UserAccountEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAccountMapper {


    List<UserAccountMapper> selectByUserId(@Param("userId")String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    int insert(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    int insertSelective(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    UserAccountEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAccountEntity record);
}