spring:
    shardingsphere:
        datasource:
            #数据源名称，多数据源以逗号分隔
            names: ds-0,ds-1
            ds-0:
                #数据库驱动类名
                driver-class-name: com.mysql.cj.jdbc.Driver
                #数据库url连接
                jdbc-url: jdbc:mysql://192.168.8.245:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                #数据库用户名
                username: root
                #数据库密码
                password: a123321
                #数据库连接池类名称
                type: com.zaxxer.hikari.HikariDataSource
            ds-1:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://192.168.8.244:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: jrl!123
                type: com.zaxxer.hikari.HikariDataSource
        sharding:
            #绑定表规则列表
            binding-tables: t_order,t_order_item
            #广播表规则列表
            broadcast-tables: t_address
            #默认数据库分片策略，同分库策略
            default-database-strategy:
                inline:
                    #分片列名称
                    sharding-column: user_id
                    #分片算法行表达式，需符合groovy语法
                    algorithm-expression: ds-$->{user_id % 2}
            #分表策略，同分库策略
            tables:
                t_order:
                    #由数据源名 + 表名组成，以小数点分隔。多个表以逗号分隔，支持inline表达式。
                    #缺省表示使用已知数据源与逻辑表名称生成数据节点。用于广播表（即每个库中都
                    #需要一个同样的表用于关联查询，多为字典表）或只分库不分表且所有库的表结构
                    #完全一致的情况
                    actual-data-nodes: ds-$->{0..1}.t_order
                    key-generator:
                        #自增列名称，缺省表示不使用自增主键生成器
                        column: order_id
                        ##默认自增列值生成器类型，缺省将使用
                        #org.apache.shardingsphere.core.keygen.generator.impl.SnowflakeKeyGenerator。
                        #可使用用户自定义的列值生成器或选择内置类型：SNOWFLAKE/UUID/LEAF_SEGMENT
                        type: SNOWFLAKE
                        #自增列值生成器属性配置, 比如SNOWFLAKE算法的worker.id与max.tolerate.time.difference.milliseconds
                        props:
                            worker:
                                id: 123
                t_order_item:
                    actual-data-nodes: ds-$->{0..1}.t_order_item
                    key-generator:
                        column: order_item_id
                        type: SNOWFLAKE
                        props:
                            worker:
                                id: 123
        props:
            sql:
                #显示sql语句
                show: true
            executor:
                #工作线程数量，默认值: CPU核数
                size: 4
