server:
    port: 8099
mybatis:
    mapper-locations: classpath:sqlmapper/*.xml
    configuration:
        aggressive-lazy-loading: true
        default-executor-type: simple
spring:
    profiles:
#        active: sharding-databases
        active: sharding-databases-tables
#logging:
#    level:
#        org.springframework: debug
#        org.mybatis: debug
